<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Player.Net._2</RootNamespace>
    <AssemblyName>Player.Net.2</AssemblyName>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJPad.Core\DJPad.Core.csproj" />
    <ProjectReference Include="..\DJPad.Interfaces\DJPad.Interfaces.csproj" />
    <ProjectReference Include="..\DJPad.UI\DJPad.UI.csproj" />
    <ProjectReference Include="..\Resources\DJPad.Resources.csproj" />
  </ItemGroup>
</Project>
