name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No user-facing changes'

categories:
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
  - title: 'Features'
    when:
      labels:
        - enhancement
        - feature
  - title: 'Fixes'
    when:
      labels:
        - bug
        - fix
  - title: 'Dependencies'
    when:
      label: 'dependencies'
  - title: 'Maintenance'
    when:
      labels:
        - chore
        - maintenance
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      label: 'release: major'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      label: 'release: minor'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      label: 'release: patch'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...v$RESOLVED_VERSION
