<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DJPad.UI</RootNamespace>
    <AssemblyName>DJPad.UI</AssemblyName>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WindowsAPICodePack-Core" Version="1.1.2" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJPad.Core\DJPad.Core.csproj" />
    <ProjectReference Include="..\DJPad.Interfaces\DJPad.Interfaces.csproj" />
    <ProjectReference Include="..\External.mp3sharp\mp3sharp\Mp3Sharp.csproj" />
    <ProjectReference Include="..\Resources\DJPad.Resources.csproj" />
  </ItemGroup>
</Project>
