<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Player.Db</RootNamespace>
    <AssemblyName>Player.Db</AssemblyName>
    <UseWPF>true</UseWPF>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJPad.Db\DJPad.Db.csproj" />
    <ProjectReference Include="..\DJPad.Interfaces\DJPad.Interfaces.csproj" />
  </ItemGroup>
</Project>
