//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:device-1-0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName = "root", Namespace = "urn:schemas-upnp-org:device-1-0", IsNullable = false)]
public partial class DeviceDescription
{
    private rootSpecVersion specVersion;
    private rootDevice device;

    [System.Xml.Serialization.XmlElementAttribute("specVersion", typeof(rootSpecVersion))]
    public rootSpecVersion SpecVersion
    {
        get
        {
            return this.specVersion;
        }
        set
        {
            this.specVersion = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device", typeof(rootDevice))]
    public rootDevice Device
    {
        get
        {
            return this.device;
        }
        set
        {
            this.device = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:device-1-0")]
public partial class rootDevice
{

    private string uDNField;

    private string friendlyNameField;

    private string deviceTypeField;

    private string manufacturerField;

    private string manufacturerURLField;

    private string modelNameField;

    private string modelNumberField;

    private string modelURLField;

    private string serialNumberField;

    private string x_DLNADOCField;

    private string magicPacketWakeSupportedField;

    private rootDeviceIconListIcon[] iconListField;

    private rootDeviceServiceListService[] serviceListField;

    /// <remarks/>
    public string UDN
    {
        get
        {
            return this.uDNField;
        }
        set
        {
            this.uDNField = value;
        }
    }

    /// <remarks/>
    public string friendlyName
    {
        get
        {
            return this.friendlyNameField;
        }
        set
        {
            this.friendlyNameField = value;
        }
    }

    /// <remarks/>
    public string deviceType
    {
        get
        {
            return this.deviceTypeField;
        }
        set
        {
            this.deviceTypeField = value;
        }
    }

    /// <remarks/>
    public string manufacturer
    {
        get
        {
            return this.manufacturerField;
        }
        set
        {
            this.manufacturerField = value;
        }
    }

    /// <remarks/>
    public string manufacturerURL
    {
        get
        {
            return this.manufacturerURLField;
        }
        set
        {
            this.manufacturerURLField = value;
        }
    }

    /// <remarks/>
    public string modelName
    {
        get
        {
            return this.modelNameField;
        }
        set
        {
            this.modelNameField = value;
        }
    }

    /// <remarks/>
    public string modelNumber
    {
        get
        {
            return this.modelNumberField;
        }
        set
        {
            this.modelNumberField = value;
        }
    }

    /// <remarks/>
    public string modelURL
    {
        get
        {
            return this.modelURLField;
        }
        set
        {
            this.modelURLField = value;
        }
    }

    /// <remarks/>
    public string serialNumber
    {
        get
        {
            return this.serialNumberField;
        }
        set
        {
            this.serialNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:schemas-dlna-org:device-1-0")]
    public string X_DLNADOC
    {
        get
        {
            return this.x_DLNADOCField;
        }
        set
        {
            this.x_DLNADOCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:schemas-microsoft-com:WMPNSS-1-0")]
    public string magicPacketWakeSupported
    {
        get
        {
            return this.magicPacketWakeSupportedField;
        }
        set
        {
            this.magicPacketWakeSupportedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("icon", typeof(rootDeviceIconListIcon), IsNullable = false)]
    public rootDeviceIconListIcon[] iconList
    {
        get
        {
            return this.iconListField;
        }
        set
        {
            this.iconListField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("service", typeof(rootDeviceServiceListService), IsNullable = false)]
    public rootDeviceServiceListService[] serviceList
    {
        get
        {
            return this.serviceListField;
        }
        set
        {
            this.serviceListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:device-1-0")]
public partial class rootDeviceIconListIcon
{

    private string mimetypeField;

    private string widthField;

    private string heightField;

    private string depthField;

    private string urlField;

    /// <remarks/>
    public string mimetype
    {
        get
        {
            return this.mimetypeField;
        }
        set
        {
            this.mimetypeField = value;
        }
    }

    /// <remarks/>
    public string width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    public string height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }

    /// <remarks/>
    public string depth
    {
        get
        {
            return this.depthField;
        }
        set
        {
            this.depthField = value;
        }
    }

    /// <remarks/>
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:device-1-0")]
public partial class rootDeviceServiceListService
{

    private string serviceTypeField;

    private string serviceIdField;

    private string controlURLField;

    private string eventSubURLField;

    private string sCPDURLField;

    /// <remarks/>
    public string serviceType
    {
        get
        {
            return this.serviceTypeField;
        }
        set
        {
            this.serviceTypeField = value;
        }
    }

    /// <remarks/>
    public string serviceId
    {
        get
        {
            return this.serviceIdField;
        }
        set
        {
            this.serviceIdField = value;
        }
    }

    /// <remarks/>
    public string controlURL
    {
        get
        {
            return this.controlURLField;
        }
        set
        {
            this.controlURLField = value;
        }
    }

    /// <remarks/>
    public string eventSubURL
    {
        get
        {
            return this.eventSubURLField;
        }
        set
        {
            this.eventSubURLField = value;
        }
    }

    /// <remarks/>
    public string SCPDURL
    {
        get
        {
            return this.sCPDURLField;
        }
        set
        {
            this.sCPDURLField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:device-1-0")]
public partial class rootSpecVersion
{

    private string majorField;

    private string minorField;

    /// <remarks/>
    public string major
    {
        get
        {
            return this.majorField;
        }
        set
        {
            this.majorField = value;
        }
    }

    /// <remarks/>
    public string minor
    {
        get
        {
            return this.minorField;
        }
        set
        {
            this.minorField = value;
        }
    }
}
