<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DJPad.Core</RootNamespace>
    <AssemblyName>DJPad.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJPad.Interfaces\DJPad.Interfaces.csproj" />
    <ProjectReference Include="..\External.mp3sharp\mp3sharp\Mp3Sharp.csproj" />
  </ItemGroup>
</Project>
