//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJPad.Db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;
    using DJPad.Core.Interfaces;
    using MongoDB.Bson.Serialization.Attributes;

    public partial class Album
    {
        public Album()
        {
            this.MediaItems = new HashSet<MediaItem>();
        }

        [BsonId]
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [MaxLength] 
        public byte[] ImageBytes { get; set; }
        
        public string Name { get; set; }
    
        public ICollection<MediaItem> MediaItems { get; set; }
    }
}
