<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DJPad.Db</RootNamespace>
    <AssemblyName>DJPad.Db</AssemblyName>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="EntityFramework.SqlServerCompact" Version="6.4.4" />
    <PackageReference Include="Microsoft.SqlServer.Compact" Version="4.0.8876.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJPad.Core\DJPad.Core.csproj" />
    <ProjectReference Include="..\DJPad.Interfaces\DJPad.Interfaces.csproj" />
  </ItemGroup>
</Project>
