//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "root.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/")]
[System.Xml.Serialization.XmlRootAttribute("DIDL-Lite", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", IsNullable = false)]
public partial class roottype
{

    /// <remarks/>
    [XmlElement("container", typeof(containertype))]
    [XmlElement("desc", typeof(desctype))]
    [XmlElement("item", typeof(itemtype))]
    public ArrayList Items;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public string lang;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "container.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/")]
public partial class containertype
{

    /// <remarks/>
    [XmlElement(Namespace = "http://purl.org/dc/elements/1.1/", Order = 0)]
    public SimpleLiteral title;

    /// <remarks/>
    [XmlElement("searchClass", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 1)]
    public searchClasstype[] searchClass;

    /// <remarks/>
    [XmlElement("createClass", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 2)]
    public searchClasstype[] createClass;

    /// <remarks/>
    [XmlElement("writeStatus", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 3)]
    public statustype[] writeStatus;

    /// <remarks/>
    [XmlElement("objectLink", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 4)]
    public objectLinktype[] objectLink;

    /// <remarks/>
    [XmlElement("objectLinkRef", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 5)]
    public objectLinkReftype[] objectLinkRef;

    /// <remarks/>
    [XmlElement("resExt", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 6)]
    public resExttype[] resExt;

    /// <remarks/>
    [XmlElement("artist", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 7)]
    public personWithRoletype[] artist;

    /// <remarks/>
    [XmlElement("actor", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 8)]
    public personWithRoletype[] actor;

    /// <remarks/>
    [XmlElement("author", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 9)]
    public personWithRoletype[] author;

    /// <remarks/>
    [XmlElement("producer", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 10)]
    public string[] producer;

    /// <remarks/>
    [XmlElement("director", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 11)]
    public string[] director;

    /// <remarks/>
    [XmlElement("genre", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 12)]
    public genretype[] genre;

    /// <remarks/>
    [XmlElement("album", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 13)]
    public string[] album;

    /// <remarks/>
    [XmlElement("playlist", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 14)]
    public string[] playlist;

    /// <remarks/>
    [XmlElement("albumArtURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI", Order = 15)]
    public string[] albumArtURI;

    /// <remarks/>
    [XmlElement("artistDiscographyURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI", Order = 16)]
    public string[] artistDiscographyURI;

    /// <remarks/>
    [XmlElement("lyricsURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI", Order = 17)]
    public string[] lyricsURI;

    /// <remarks/>
    [XmlElement("storageTotal", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 18)]
    public long[] storageTotal;

    /// <remarks/>
    [XmlElement("storageUsed", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 19)]
    public long[] storageUsed;

    /// <remarks/>
    [XmlElement("storageFree", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 20)]
    public long[] storageFree;

    /// <remarks/>
    [XmlElement("storageMaxPartition", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 21)]
    public long[] storageMaxPartition;

    /// <remarks/>
    [XmlElement("storageMedium", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 22)]
    public string[] storageMedium;

    /// <remarks/>
    [XmlElement("longDescription", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 23)]
    public string[] longDescription;

    /// <remarks/>
    [XmlElement("icon", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI", Order = 24)]
    public string[] icon;

    /// <remarks/>
    [XmlElement("region", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 25)]
    public string[] region;

    /// <remarks/>
    [XmlElement("rights", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 26)]
    public string[] rights;

    /// <remarks/>
    [XmlElement("playbackCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 27)]
    public int[] playbackCount;

    /// <remarks/>
    [XmlElement("lastPlaybackTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 28)]
    public qualifiedDateTime[] lastPlaybackTime;

    /// <remarks/>
    [XmlElement("lastPlaybackPosition", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 29)]
    public string[] lastPlaybackPosition;

    /// <remarks/>
    [XmlElement("recordedStartDateTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 30)]
    public qualifiedDateTime[] recordedStartDateTime;

    /// <remarks/>
    [XmlElement("recordedEndDateTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 31)]
    public qualifiedDateTime[] recordedEndDateTime;

    /// <remarks/>
    [XmlElement("recordedDuration", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 32)]
    public string[] recordedDuration;

    /// <remarks/>
    [XmlElement("recordedDayOfWeek", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 33)]
    public dayOfWeekenlen3[] recordedDayOfWeek;

    /// <remarks/>
    [XmlElement("srsRecordSchedule", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 34)]
    public string[] srsRecordSchedule;

    /// <remarks/>
    [XmlElement("srsRecordTaskID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 35)]
    public string[] srsRecordTaskID;

    /// <remarks/>
    [XmlElement("recordable", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 36)]
    public bool[] recordable;

    /// <remarks/>
    [XmlElement("programTitle", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 37)]
    public string[] programTitle;

    /// <remarks/>
    [XmlElement("seriesTitle", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 38)]
    public string[] seriesTitle;

    /// <remarks/>
    [XmlElement("programID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 39)]
    public programIDtype[] programID;

    /// <remarks/>
    [XmlElement("seriesID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 40)]
    public programIDtype[] seriesID;

    /// <remarks/>
    [XmlElement("channelID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 41)]
    public channelIDtype[] channelID;

    /// <remarks/>
    [XmlElement("episodeCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 42)]
    public uint[] episodeCount;

    /// <remarks/>
    [XmlElement("episodeNumber", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 43)]
    public uint[] episodeNumber;

    /// <remarks/>
    [XmlElement("episodeSeason", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 44)]
    public uint[] episodeSeason;

    /// <remarks/>
    [XmlElement("programCode", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 45)]
    public programCodetype[] programCode;

    /// <remarks/>
    [XmlElement("rating", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 46)]
    public ratingtype[] rating;

    /// <remarks/>
    [XmlElement("episodeType", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 47)]
    public string[] episodeType;

    /// <remarks/>
    [XmlElement("programPreserved", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 48)]
    public programPreservedType[] programPreserved;

    /// <remarks/>
    [XmlElement("preservedTimeRange", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 49)]
    public preservedTimeRangeType[] preservedTimeRange;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 50)]
    [System.Xml.Serialization.XmlArrayItemAttribute("program", typeof(programListTypeProgram), IsNullable = false)]
    public programListTypeProgram[] programList;

    /// <remarks/>
    [XmlElement("recommendationID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 51)]
    public recommendationIDtype[] recommendationID;

    /// <remarks/>
    [XmlElement("channelGroupName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 52)]
    public channelGroupNametype[] channelGroupName;

    /// <remarks/>
    [XmlElement("callSign", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 53)]
    public string[] callSign;

    /// <remarks/>
    [XmlElement("networkAffiliation", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 54)]
    public string[] networkAffiliation;

    /// <remarks/>
    [XmlElement("serviceProvider", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 55)]
    public string[] serviceProvider;

    /// <remarks/>
    [XmlElement("price", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 56)]
    public pricetype[] price;

    /// <remarks/>
    [XmlElement("payPerView", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 57)]
    public bool[] payPerView;

    /// <remarks/>
    [XmlElement("epgProviderName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 58)]
    public string[] epgProviderName;

    /// <remarks/>
    [XmlElement("dateTimeRange", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 59)]
    public qualifiedDateTimerange[] dateTimeRange;

    /// <remarks/>
    [XmlElement("radioCallSign", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 60)]
    public string[] radioCallSign;

    /// <remarks/>
    [XmlElement("radioStationID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 61)]
    public string[] radioStationID;

    /// <remarks/>
    [XmlElement("radioBand", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 62)]
    public string[] radioBand;

    /// <remarks/>
    [XmlElement("channelNr", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 63)]
    public int[] channelNr;

    /// <remarks/>
    [XmlElement("channelName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 64)]
    public string[] channelName;

    /// <remarks/>
    [XmlElement("scheduledStartTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 65)]
    public qualifiedDateTimeISO8601[] scheduledStartTime;

    /// <remarks/>
    [XmlElement("scheduledEndTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 66)]
    public qualifiedDateTimeISO8601[] scheduledEndTime;

    /// <remarks/>
    [XmlElement("scheduledDuration", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 67)]
    public string[] scheduledDuration;

    /// <remarks/>
    [XmlElement("signalStrength", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 68)]
    public string[] signalStrength;

    /// <remarks/>
    [XmlElement("signalLocked", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 69)]
    public bool[] signalLocked;

    /// <remarks/>
    [XmlElement("tuned", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 70)]
    public bool[] tuned;

    /// <remarks/>
    [XmlElement("bookmarkID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 71)]
    public string[] bookmarkID;

    /// <remarks/>
    [XmlElement("bookmarkedObjectID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 72)]
    public string[] bookmarkedObjectID;

    /// <remarks/>
    [XmlElement("deviceUDN", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 73)]
    public deviceUDNtype[] deviceUDN;

    /// <remarks/>
    [XmlElement("stateVariableCollection", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 74)]
    public stateVariableCollectiontype[] stateVariableCollection;

    /// <remarks/>
    [XmlElement("foreignMetadata", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 75)]
    public foreignMetadatatype[] foreignMetadata;

    /// <remarks/>
    [XmlElement("DVDRegionCode", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 76)]
    public int[] DVDRegionCode;

    /// <remarks/>
    [XmlElement("originalTrackNumber", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 77)]
    public int[] originalTrackNumber;

    /// <remarks/>
    [XmlElement("toc", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 78)]
    public string[] toc;

    /// <remarks/>
    [XmlElement("userAnnotation", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 79)]
    public string[] userAnnotation;

    /// <remarks/>
    [XmlElement("containerUpdateID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 80)]
    public uint[] containerUpdateID;

    /// <remarks/>
    [XmlElement("objectUpdateID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 81)]
    public uint[] objectUpdateID;

    /// <remarks/>
    [XmlElement("totalDeletedChildCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 82)]
    public uint[] totalDeletedChildCount;

    /// <remarks/>
    [XmlElement("segmentID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 83)]
    public string[] segmentID;

    /// <remarks/>
    [XmlElement("objectOwner", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 84)]
    public ownerType[] objectOwner;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 85)]
    [System.Xml.Serialization.XmlArrayItemAttribute("role", typeof(string), IsNullable = false)]
    public string[] inclusionControl;

    /// <remarks/>
    [XmlElement("contributor", Namespace = "http://purl.org/dc/elements/1.1/", Order = 86)]
    public SimpleLiteral[] contributor;

    /// <remarks/>
    [XmlElement("creator", Namespace = "http://purl.org/dc/elements/1.1/", Order = 87)]
    public SimpleLiteral[] creator;

    /// <remarks/>
    [XmlElement("date", Namespace = "http://purl.org/dc/elements/1.1/", Order = 88)]
    public SimpleLiteral[] date;

    /// <remarks/>
    [XmlElement("description", Namespace = "http://purl.org/dc/elements/1.1/", Order = 89)]
    public SimpleLiteral[] description;

    /// <remarks/>
    [XmlElement("language", Namespace = "http://purl.org/dc/elements/1.1/", Order = 90)]
    public SimpleLiteral[] language;

    /// <remarks/>
    [XmlElement("publisher", Namespace = "http://purl.org/dc/elements/1.1/", Order = 91)]
    public SimpleLiteral[] publisher;

    /// <remarks/>
    [XmlElement("relation", Namespace = "http://purl.org/dc/elements/1.1/", Order = 92)]
    public SimpleLiteral[] relation;

    /// <remarks/>
    [XmlElement("rights", Namespace = "http://purl.org/dc/elements/1.1/", Order = 93)]
    public SimpleLiteral[] rights1;

    /// <remarks/>
    [XmlElement("desc", Order = 94)]
    public desctype[] desc;

    /// <remarks/>
    [XmlElement("item", Order = 95)]
    public itemtype[] item;

    /// <remarks/>
    [XmlElement("container", Order = 96)]
    public containertype[] container;

    /// <remarks/>
    [XmlElement("res", Order = 97)]
    public restype[] res;

    /// <remarks/>
    [XmlElement(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", Order = 98)]
    public classtype @class;
   
    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [XmlAttribute]
    public string parentID;

    /// <remarks/>
    [XmlAttribute]
    public bool restricted;

    /// <remarks/>
    [XmlAttribute]
    public bool neverPlayable;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool neverPlayableSpecified;

    /// <remarks/>
    [XmlAttribute]
    public bool searchable;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool searchableSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint childCount;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool childCountSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint childContainerCount;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool childContainerCountSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purl.org/dc/elements/1.1/")]
[System.Xml.Serialization.XmlRootAttribute("title", Namespace = "http://purl.org/dc/elements/1.1/", IsNullable = false)]
public partial class SimpleLiteral
{

    /// <remarks/>
    [XmlText]
    public string Text;

    public override string ToString()
    {
        return this.Text;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purl.org/dc/elements/1.1/")]
public partial class elementContainer
{

    /// <remarks/>
    [XmlElement("any", typeof(SimpleLiteral))]
    [XmlElement("contributor", typeof(SimpleLiteral))]
    [XmlElement("coverage", typeof(SimpleLiteral))]
    [XmlElement("creator", typeof(SimpleLiteral))]
    [XmlElement("date", typeof(SimpleLiteral))]
    [XmlElement("description", typeof(SimpleLiteral))]
    [XmlElement("format", typeof(SimpleLiteral))]
    [XmlElement("identifier", typeof(SimpleLiteral))]
    [XmlElement("language", typeof(SimpleLiteral))]
    [XmlElement("publisher", typeof(SimpleLiteral))]
    [XmlElement("relation", typeof(SimpleLiteral))]
    [XmlElement("rights", typeof(SimpleLiteral))]
    [XmlElement("source", typeof(SimpleLiteral))]
    [XmlElement("subject", typeof(SimpleLiteral))]
    [XmlElement("title", typeof(SimpleLiteral))]
    [XmlElement("type", typeof(SimpleLiteral))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public SimpleLiteral[] Items;

    /// <remarks/>
    [XmlElement("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purl.org/dc/elements/1.1/", IncludeInSchema = false)]
public enum ItemsChoiceType
{

    /// <remarks/>
    any,

    /// <remarks/>
    contributor,

    /// <remarks/>
    coverage,

    /// <remarks/>
    creator,

    /// <remarks/>
    date,

    /// <remarks/>
    description,

    /// <remarks/>
    format,

    /// <remarks/>
    identifier,

    /// <remarks/>
    language,

    /// <remarks/>
    publisher,

    /// <remarks/>
    relation,

    /// <remarks/>
    rights,

    /// <remarks/>
    source,

    /// <remarks/>
    subject,

    /// <remarks/>
    title,

    /// <remarks/>
    type,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "stateVariable.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class stateVariabletype
{

    /// <remarks/>
    [XmlAttribute]
    public string variableName;

    /// <remarks/>
    [XmlAttribute]
    public string channel;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "storageMedium.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class storageMediumtype
{

    /// <remarks/>
    [XmlAttribute]
    public string val;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "res.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/")]
public partial class restype
{

    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string importUri;

    /// <remarks/>
    [XmlAttribute]
    public string protocolInfo;

    /// <remarks/>
    [XmlAttribute]
    public ulong size;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string duration;

    /// <remarks/>
    [XmlAttribute]
    public uint bitrate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitrateSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint sampleFrequency;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleFrequencySpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint bitsPerSample;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitsPerSampleSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint nrAudioChannels;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nrAudioChannelsSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string resolution;

    /// <remarks/>
    [XmlAttribute]
    public uint colorDepth;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool colorDepthSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string tspec;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string allowedUse;

    /// <remarks/>
    [XmlAttribute]
    public System.DateTime validityStart;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityStartSpecified;

    /// <remarks/>
    [XmlAttribute]
    public System.DateTime validityEnd;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityEndSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string remainingTime;

    /// <remarks/>
    [XmlAttribute]
    public uint updateCount;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool updateCountSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string usageInfo;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string rightsInfoURI;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string contentInfoURI;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string recordQuality;

    /// <remarks/>
    [XmlAttribute]
    public string protection;

    /// <remarks/>
    [XmlAttribute]
    public string framerate;

    /// <remarks/>
    [XmlAttribute]
    public daylightSavingtype daylightSaving;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daylightSavingSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "daylightSaving.type", Namespace = "urn:schemas-upnp-org:av:av")]
public enum daylightSavingtype
{

    /// <remarks/>
    DAYLIGHTSAVING,

    /// <remarks/>
    STANDARD,

    /// <remarks/>
    UNKNOWN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "desc.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/")]
public partial class desctype
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any;

    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string nameSpace;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "owner.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class ownerType
{

    /// <remarks/>
    [XmlElement("role")]
    public string[] role;

    /// <remarks/>
    [XmlAttribute]
    public bool @lock;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "stateVariableCollection.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class stateVariableCollectiontype
{

    /// <remarks/>
    [XmlAttribute]
    public stateVariableCollectiontypeServiceName serviceName;

    /// <remarks/>
    [XmlAttribute]
    public stateVariableCollectiontypeRcsInstanceType rcsInstanceType;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool rcsInstanceTypeSpecified;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public enum stateVariableCollectiontypeServiceName
{

    /// <remarks/>
    AVTransport,

    /// <remarks/>
    RenderingControl,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public enum stateVariableCollectiontypeRcsInstanceType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("pre-mix")]
    premix,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("post-mix")]
    postmix,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "deviceUDN.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class deviceUDNtype
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string serviceType;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string serviceId;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "qualifiedDateTime.ISO8601", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class qualifiedDateTimeISO8601
{

    /// <remarks/>
    [XmlAttribute]
    public daylightSavingtype daylightSaving;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daylightSavingSpecified;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "qualifiedDateTime-range", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class qualifiedDateTimerange
{

    /// <remarks/>
    [XmlAttribute]
    public daylightSavingtype daylightSaving;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daylightSavingSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "price.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class pricetype
{

    /// <remarks/>
    [XmlAttribute]
    public string currency;

    /// <remarks/>
    [XmlText]
    public float Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "channelGroupName.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class channelGroupNametype
{

    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "recommendationID.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class recommendationIDtype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "preservedTimeRange.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class preservedTimeRangeType
{

    /// <remarks/>
    [XmlAttribute]
    public string startTime;

    /// <remarks/>
    [XmlAttribute]
    public string startTimeDaylightSaving;

    /// <remarks/>
    [XmlAttribute]
    public string endTime;

    /// <remarks/>
    [XmlAttribute]
    public string endTimeDaylightSaving;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "programPreserved.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class programPreservedType
{

    /// <remarks/>
    [XmlAttribute]
    public string startTime;

    /// <remarks/>
    [XmlAttribute]
    public string startTimeDaylightSaving;

    /// <remarks/>
    [XmlAttribute]
    public string endTime;

    /// <remarks/>
    [XmlAttribute]
    public string endTimeDaylightSaving;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "rating.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class ratingtype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [XmlAttribute]
    public string advice;

    /// <remarks/>
    [XmlAttribute]
    public string equivalentAge;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "programCode.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class programCodetype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "channelID.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class channelIDtype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "programID.type", Namespace = "urn:schemas-upnp-org:av:av")]
public partial class programIDtype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class qualifiedDateTime
{

    /// <remarks/>
    [XmlAttribute]
    public daylightSavingtype daylightSaving;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daylightSavingSpecified;

    /// <remarks/>
    [XmlText]
    public System.DateTime Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "genre.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class genretype
{

    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [XmlAttribute]
    public string extended;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "personWithRole.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class personWithRoletype
{

    /// <remarks/>
    [XmlAttribute]
    public string role;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "uniqueContentIdentification.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class uniqueContentIdentificationtype
{

    /// <remarks/>
    [XmlAttribute]
    public string type;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "upnp.res.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class upnprestype
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string importUri;

    /// <remarks/>
    [XmlAttribute]
    public string protocolInfo;

    /// <remarks/>
    [XmlAttribute]
    public ulong size;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sizeSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string duration;

    /// <remarks/>
    [XmlAttribute]
    public uint bitrate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitrateSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint sampleFrequency;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleFrequencySpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint bitsPerSample;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitsPerSampleSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint nrAudioChannels;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nrAudioChannelsSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string resolution;

    /// <remarks/>
    [XmlAttribute]
    public uint colorDepth;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool colorDepthSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string tspec;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string allowedUse;

    /// <remarks/>
    [XmlAttribute]
    public System.DateTime validityStart;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityStartSpecified;

    /// <remarks/>
    [XmlAttribute]
    public System.DateTime validityEnd;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityEndSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string remainingTime;

    /// <remarks/>
    [XmlAttribute]
    public string usageInfo;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string rightsInfoURI;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
    public string contentInfoURI;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string recordQuality;

    /// <remarks/>
    [XmlAttribute]
    public string protection;

    /// <remarks/>
    [XmlAttribute]
    public daylightSavingtype daylightSaving;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool daylightSavingSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "compRes.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class compResType
{

    /// <remarks/>
    public string isSynchAnchor;

    /// <remarks/>
    public string refUDN;

    /// <remarks/>
    public string refObjectID;

    /// <remarks/>
    public string refResID;

    /// <remarks/>
    [XmlElement("res")]
    public upnprestype[] res;

    /// <remarks/>
    [XmlText]
    public string[] Text;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "contentType.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class contentTypeType
{

    /// <remarks/>
    [XmlAttribute]
    public string MIMEType;

    /// <remarks/>
    [XmlAttribute]
    public string extendedType;

    /// <remarks/>
    [XmlAttribute]
    public string protection;

    /// <remarks/>
    [XmlAttribute]
    public uint bitrate;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitrateSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint bitPerSample;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bitPerSampleSpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint sampleFrequency;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sampleFrequencySpecified;

    /// <remarks/>
    [XmlAttribute]
    public uint nrAudioChannels;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nrAudioChannelsSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string resolution;

    /// <remarks/>
    [XmlAttribute]
    public uint colorDepth;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool colorDepthSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string framerate;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "component.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class componentType
{

    /// <remarks/>
    public string componentClass;

    /// <remarks/>
    public contentTypeType contentType;

    /// <remarks/>
    public string language;

    /// <remarks/>
    public compResType compRes;

    /// <remarks/>
    [XmlAttribute]
    public string componentID;

    /// <remarks/>
    [XmlAttribute]
    public bool supportive;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool supportiveSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string supportID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "componentGroup.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class componentGroupType
{

    /// <remarks/>
    [XmlElement("component")]
    public componentType[] component;

    /// <remarks/>
    [XmlAttribute]
    public string groupID;

    /// <remarks/>
    [XmlAttribute]
    public bool required;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "componentInfo.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class componentInfoType
{

    /// <remarks/>
    [XmlElement("componentGroup")]
    public componentGroupType[] componentGroup;

    /// <remarks/>
    [XmlAttribute]
    public string componentID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "DRMInfo.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class DRMInfoType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("foreignMetaData", typeof(foreignMetadatatype), IsNullable = false)]
    public foreignMetadatatype[] DRMInfo;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "foreignMetadata.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class foreignMetadatatype
{

    /// <remarks/>
    [XmlElement("fmId")]
    public string[] fmId;

    /// <remarks/>
    [XmlElement("fmClass")]
    public string[] fmClass;

    /// <remarks/>
    [XmlElement("fmProvider")]
    public string[] fmProvider;

    /// <remarks/>
    [XmlElement("fmBody")]
    public fmelementsbodytype[] fmBody;

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any;

    /// <remarks/>
    [XmlAttribute]
    public string type;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "fm.elements.body.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class fmelementsbodytype
{

    /// <remarks/>
    [XmlElement("fmEmbeddedString", typeof(fmelementsbodyembeddedStringtype))]
    [XmlElement("fmEmbeddedXML", typeof(fmelementsbodyembeddedXMLtype))]
    [XmlElement("fmURI", typeof(fmelementsbodyuritype))]
    public object Item;

    /// <remarks/>
    [XmlAttribute]
    public bool xmlFlag;

    /// <remarks/>
    [XmlAttribute]
    public string mimeType;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "fm.elements.body.embeddedString.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class fmelementsbodyembeddedStringtype
{

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "fm.elements.body.embeddedXML.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class fmelementsbodyembeddedXMLtype
{

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Items;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "fm.elements.body.uri.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class fmelementsbodyuritype
{

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType = "anyURI")]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "clockSync.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class clockSyncType
{

    /// <remarks/>
    [XmlAttribute]
    public string deviceClockInfoID;

    /// <remarks/>
    [XmlAttribute]
    public string supportedTimestampsID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "segmentInfo.Type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class segmentInfoType
{

    /// <remarks/>
    public segmentInfoTypeTimeRange timeRange;

    /// <remarks/>
    public segmentInfoTypeByteRange byteRange;

    /// <remarks/>
    public segmentInfoTypeFrameRange frameRange;

    /// <remarks/>
    [XmlAttribute]
    public string baseObjectID;

    /// <remarks/>
    [XmlAttribute]
    public string baseResID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class segmentInfoTypeTimeRange
{

    /// <remarks/>
    [XmlAttribute]
    public string start;

    /// <remarks/>
    [XmlAttribute]
    public string end;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class segmentInfoTypeByteRange
{

    /// <remarks/>
    [XmlAttribute]
    public ulong start;

    /// <remarks/>
    [XmlAttribute]
    public ulong end;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class segmentInfoTypeFrameRange
{

    /// <remarks/>
    [XmlAttribute]
    public ulong start;

    /// <remarks/>
    [XmlAttribute]
    public ulong end;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "resExt.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class resExttype
{

    /// <remarks/>
    [XmlElement("DRMInfo", typeof(DRMInfoType))]
    [XmlElement("clockSync", typeof(clockSyncType))]
    [XmlElement("componentInfo", typeof(componentInfoType))]
    [XmlElement("isSyncAnchor", typeof(string))]
    [XmlElement("segmentInfo", typeof(segmentInfoType))]
    [XmlElement("uniqueContentIdentification", typeof(uniqueContentIdentificationtype))]
    public object[] Items;

    /// <remarks/>
    [XmlAttribute]
    public string id;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "objectLinkRef.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinkReftype
{

    /// <remarks/>
    [XmlElement("relatedInfo", typeof(objectLinkReftypeRelatedInfo))]
    [XmlElement("startObject", typeof(bool))]
    [XmlElement("title", typeof(object))]
    public object Item;

    /// <remarks/>
    [XmlAttribute]
    public string groupID;

    /// <remarks/>
    [XmlAttribute]
    public string targetGroup;

    /// <remarks/>
    [XmlAttribute]
    public string targetObjID;

    /// <remarks/>
    [XmlAttribute]
    public bool @return;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool returnSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinkReftypeRelatedInfo
{

    /// <remarks/>
    [XmlAttribute]
    public string role;

    /// <remarks/>
    [XmlAttribute]
    public string roleText;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "objectLink.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinktype
{

    /// <remarks/>
    [XmlElement("endAction", typeof(objectLinktypeEndAction))]
    [XmlElement("mode", typeof(objectLinktypeMode))]
    [XmlElement("relatedInfo", typeof(objectLinktypeRelatedInfo))]
    [XmlElement("startInfo", typeof(objectLinktypeStartInfo))]
    [XmlElement("startObject", typeof(bool))]
    [XmlElement("title", typeof(string))]
    public object[] Items;

    /// <remarks/>
    [XmlAttribute]
    public string groupID;

    /// <remarks/>
    [XmlAttribute]
    public string headObjID;

    /// <remarks/>
    [XmlAttribute]
    public string nextObjID;

    /// <remarks/>
    [XmlAttribute]
    public string prevObjID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinktypeEndAction
{

    /// <remarks/>
    [XmlAttribute]
    public objectLinktypeEndActionAction action;

    /// <remarks/>
    [XmlAttribute]
    public string targetGroupID;

    /// <remarks/>
    [XmlAttribute]
    public string targetObjID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public enum objectLinktypeEndActionAction
{

    /// <remarks/>
    Return,

    /// <remarks/>
    Branch,

    /// <remarks/>
    Stop,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public enum objectLinktypeMode
{

    /// <remarks/>
    Playback,

    /// <remarks/>
    Step,

    /// <remarks/>
    Index,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinktypeRelatedInfo
{

    /// <remarks/>
    [XmlAttribute]
    public string role;

    /// <remarks/>
    [XmlAttribute]
    public string roleText;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class objectLinktypeStartInfo
{

    /// <remarks/>
    [XmlAttribute]
    public string targetGroupID;

    /// <remarks/>
    [XmlAttribute]
    public string targetObjID;
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(searchClasstype))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "class.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class classtype
{

    /// <remarks/>
    [XmlAttribute]
    public string name;

    /// <remarks/>
    [XmlText]
    public string Value;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "searchClass.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class searchClasstype : classtype
{

    /// <remarks/>
    [XmlAttribute]
    public bool includeDerived;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "item.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/")]
public partial class itemtype
{
    public override string ToString()
    {
        return this.id + " " + (this.title != null ? this.title.ToString() : string.Empty);
    }

    /// <remarks/>
    [XmlElement(Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] title;

    /// <remarks/>
    [XmlElement("searchClass", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public searchClasstype[] searchClass;

    /// <remarks/>
    [XmlElement("createClass", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public searchClasstype[] createClass;

    /// <remarks/>
    [XmlElement("writeStatus", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public statustype[] writeStatus;

    /// <remarks/>
    [XmlElement("objectLink", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public objectLinktype[] objectLink;

    /// <remarks/>
    [XmlElement("objectLinkRef", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public objectLinkReftype[] objectLinkRef;

    /// <remarks/>
    [XmlElement("resExt", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public resExttype[] resExt;

    /// <remarks/>
    [XmlElement("artist", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public personWithRoletype[] artist;

    /// <remarks/>
    [XmlElement("actor", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public personWithRoletype[] actor;

    /// <remarks/>
    [XmlElement("author", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public personWithRoletype[] author;

    /// <remarks/>
    [XmlElement("producer", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] producer;

    /// <remarks/>
    [XmlElement("director", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] director;

    /// <remarks/>
    [XmlElement("genre", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public genretype[] genre;

    /// <remarks/>
    [XmlElement("album", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] album;

    /// <remarks/>
    [XmlElement("playlist", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] playlist;

    /// <remarks/>
    [XmlElement("albumArtURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI")]
    public string[] albumArtURI;

    /// <remarks/>
    [XmlElement("artistDiscographyURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI")]
    public string[] artistDiscographyURI;

    /// <remarks/>
    [XmlElement("lyricsURI", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI")]
    public string[] lyricsURI;

    /// <remarks/>
    [XmlElement("storageTotal", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public long[] storageTotal;

    /// <remarks/>
    [XmlElement("storageUsed", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public long[] storageUsed;

    /// <remarks/>
    [XmlElement("storageFree", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public long[] storageFree;

    /// <remarks/>
    [XmlElement("storageMaxPartition", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public long[] storageMaxPartition;

    /// <remarks/>
    [XmlElement("storageMedium", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] storageMedium;

    /// <remarks/>
    [XmlElement("longDescription", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] longDescription;

    /// <remarks/>
    [XmlElement("icon", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", DataType = "anyURI")]
    public string[] icon;

    /// <remarks/>
    [XmlElement("region", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] region;

    /// <remarks/>
    [XmlElement("rights", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] rights;

    /// <remarks/>
    [XmlElement("playbackCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public int[] playbackCount;

    /// <remarks/>
    [XmlElement("lastPlaybackTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTime[] lastPlaybackTime;

    /// <remarks/>
    [XmlElement("lastPlaybackPosition", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] lastPlaybackPosition;

    /// <remarks/>
    [XmlElement("recordedStartDateTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTime[] recordedStartDateTime;

    /// <remarks/>
    [XmlElement("recordedEndDateTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTime[] recordedEndDateTime;

    /// <remarks/>
    [XmlElement("recordedDuration", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] recordedDuration;

    /// <remarks/>
    [XmlElement("recordedDayOfWeek", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public dayOfWeekenlen3[] recordedDayOfWeek;

    /// <remarks/>
    [XmlElement("srsRecordSchedule", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] srsRecordSchedule;

    /// <remarks/>
    [XmlElement("srsRecordTaskID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] srsRecordTaskID;

    /// <remarks/>
    [XmlElement("recordable", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public bool[] recordable;

    /// <remarks/>
    [XmlElement("programTitle", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] programTitle;

    /// <remarks/>
    [XmlElement("seriesTitle", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] seriesTitle;

    /// <remarks/>
    [XmlElement("programID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public programIDtype[] programID;

    /// <remarks/>
    [XmlElement("seriesID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public programIDtype[] seriesID;

    /// <remarks/>
    [XmlElement("channelID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public channelIDtype[] channelID;

    /// <remarks/>
    [XmlElement("episodeCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] episodeCount;

    /// <remarks/>
    [XmlElement("episodeNumber", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] episodeNumber;

    /// <remarks/>
    [XmlElement("episodeSeason", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] episodeSeason;

    /// <remarks/>
    [XmlElement("programCode", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public programCodetype[] programCode;

    /// <remarks/>
    [XmlElement("rating", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public ratingtype[] rating;

    /// <remarks/>
    [XmlElement("episodeType", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] episodeType;

    /// <remarks/>
    [XmlElement("programPreserved", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public programPreservedType[] programPreserved;

    /// <remarks/>
    [XmlElement("preservedTimeRange", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public preservedTimeRangeType[] preservedTimeRange;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    [System.Xml.Serialization.XmlArrayItemAttribute("program", typeof(programListTypeProgram), IsNullable = false)]
    public programListTypeProgram[] programList;

    /// <remarks/>
    [XmlElement("recommendationID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public recommendationIDtype[] recommendationID;

    /// <remarks/>
    [XmlElement("channelGroupName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public channelGroupNametype[] channelGroupName;

    /// <remarks/>
    [XmlElement("callSign", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] callSign;

    /// <remarks/>
    [XmlElement("networkAffiliation", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] networkAffiliation;

    /// <remarks/>
    [XmlElement("serviceProvider", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] serviceProvider;

    /// <remarks/>
    [XmlElement("price", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public pricetype[] price;

    /// <remarks/>
    [XmlElement("payPerView", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public bool[] payPerView;

    /// <remarks/>
    [XmlElement("epgProviderName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] epgProviderName;

    /// <remarks/>
    [XmlElement("dateTimeRange", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTimerange[] dateTimeRange;

    /// <remarks/>
    [XmlElement("radioCallSign", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] radioCallSign;

    /// <remarks/>
    [XmlElement("radioStationID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] radioStationID;

    /// <remarks/>
    [XmlElement("radioBand", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] radioBand;

    /// <remarks/>
    [XmlElement("channelNr", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public int[] channelNr;

    /// <remarks/>
    [XmlElement("channelName", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] channelName;

    /// <remarks/>
    [XmlElement("scheduledStartTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTimeISO8601[] scheduledStartTime;

    /// <remarks/>
    [XmlElement("scheduledEndTime", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public qualifiedDateTimeISO8601[] scheduledEndTime;

    /// <remarks/>
    [XmlElement("scheduledDuration", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] scheduledDuration;

    /// <remarks/>
    [XmlElement("signalStrength", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] signalStrength;

    /// <remarks/>
    [XmlElement("signalLocked", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public bool[] signalLocked;

    /// <remarks/>
    [XmlElement("tuned", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public bool[] tuned;

    /// <remarks/>
    [XmlElement("bookmarkID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] bookmarkID;

    /// <remarks/>
    [XmlElement("bookmarkedObjectID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] bookmarkedObjectID;

    /// <remarks/>
    [XmlElement("deviceUDN", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public deviceUDNtype[] deviceUDN;

    /// <remarks/>
    [XmlElement("stateVariableCollection", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public stateVariableCollectiontype[] stateVariableCollection;

    /// <remarks/>
    [XmlElement("foreignMetadata", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public foreignMetadatatype[] foreignMetadata;

    /// <remarks/>
    [XmlElement("DVDRegionCode", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public int[] DVDRegionCode;

    /// <remarks/>
    [XmlElement("originalTrackNumber", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public int[] originalTrackNumber;

    /// <remarks/>
    [XmlElement("toc", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] toc;

    /// <remarks/>
    [XmlElement("userAnnotation", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] userAnnotation;

    /// <remarks/>
    [XmlElement("containerUpdateID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] containerUpdateID;

    /// <remarks/>
    [XmlElement("objectUpdateID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] objectUpdateID;

    /// <remarks/>
    [XmlElement("totalDeletedChildCount", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public uint[] totalDeletedChildCount;

    /// <remarks/>
    [XmlElement("segmentID", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public string[] segmentID;

    /// <remarks/>
    [XmlElement("objectOwner", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public ownerType[] objectOwner;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    [System.Xml.Serialization.XmlArrayItemAttribute("role", typeof(string), IsNullable = false)]
    public string[] inclusionControl;

    /// <remarks/>
    [XmlElement("contributor", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] contributor;

    /// <remarks/>
    [XmlElement("creator", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] creator;

    /// <remarks/>
    [XmlElement("date", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] date;

    /// <remarks/>
    [XmlElement("description", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] description;

    /// <remarks/>
    [XmlElement("language", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] language;

    /// <remarks/>
    [XmlElement("publisher", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] publisher;

    /// <remarks/>
    [XmlElement("relation", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] relation;

    /// <remarks/>
    [XmlElement("rights", Namespace = "http://purl.org/dc/elements/1.1/")]
    public SimpleLiteral[] rights1;

    /// <remarks/>
    [XmlElement("desc")]
    public desctype[] desc;

    /// <remarks/>
    [XmlElement("res")]
    public restype res;

    /// <remarks/>
    [XmlElement(Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
    public classtype @class;

    /// <remarks/>
    [XmlAttribute]
    public string id;

    /// <remarks/>
    [XmlAttribute]
    public string parentID;

    /// <remarks/>
    [XmlAttribute]
    public bool restricted;

    /// <remarks/>
    [XmlAttribute]
    public bool neverPlayable;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool neverPlayableSpecified;

    /// <remarks/>
    [XmlAttribute]
    public string refID;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "status.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public enum statustype
{

    /// <remarks/>
    WRITABLE,

    /// <remarks/>
    PROTECTED,

    /// <remarks/>
    NOT_WRITABLE,

    /// <remarks/>
    UNKNOWN,

    /// <remarks/>
    MIXED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName = "dayOfWeek.en.len.3", Namespace = "urn:schemas-upnp-org:av:av")]
public enum dayOfWeekenlen3
{

    /// <remarks/>
    SUN,

    /// <remarks/>
    MON,

    /// <remarks/>
    TUE,

    /// <remarks/>
    WED,

    /// <remarks/>
    THU,

    /// <remarks/>
    FRI,

    /// <remarks/>
    SAT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/")]
public partial class programListTypeProgram
{

    /// <remarks/>
    [XmlAttribute]
    public string preserved;

    /// <remarks/>
    [XmlText]
    public string Value;
}
